### ISSUE TITLE
Make EnvoyExtensionPolicy buffersize configurable

### ISSUE THREAD

**Issue by ion-elgreco** [envoyproxy/ai-gateway#798]
*Description*:
The default EnvoyExtensionPolicy has a low buffer size set to 50Mi, this is causing some requests to fail for me. Unfortunately it's hardcoded inside the AIGW, so I have to manually patch the manifests.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ion-elgreco** [comment]
Trying to patch the connection limit unfortunately doesn't apply even with rolled restart, it still returns a 413

```yaml
spec:
  extProc:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: envoy-ai-gateway-extproc-backend
      namespace: default
    backendSettings:
      connection:
        bufferLimit: 500Mi
```
